const LOCAL_STORAGE_USER = 'User';
const LOCAL_STORAGE_SESSION_TIME = 'SessionTime';
const LOCAL_STORAGE_AUTH_TOKEN = 'authToken';
const LOCAL_STORAGE_GRID_SETTINGS = 'gridSettings';

export {
  LOCAL_STORAGE_USER,
  LOCAL_STORAGE_SESSION_TIME,
  LOCAL_STORAGE_AUTH_TOKEN,
  LOCAL_STORAGE_GRID_SETTINGS,
};
