export enum UserPermission {
  SUPER_ADMIN_PERMISSION = 'SUPER_ADMIN_PERMISSION',
  ADMIN_PERMISSION = 'ADMIN_PERMISSION',
  SEO_PERMISSION = 'SEO_PERMISSION',
  USER_PERMISSION = 'USER_PERMISSION',
}
