export enum Routes {
  HOME = '',
  CATALOG = 'catalog',
  ABOUT = 'about',
  DISCOUNTS = 'discounts',
  CALCULATOR = 'calculator',
  REVIEWS = 'reviews',
  DEALERS = 'dealers',
  INNOVATIONS = 'innovations',
  COOPERATION = 'cooperation',
  CONTACTS = 'contacts',
  NEWS = 'company-life',
  PHOTOGALLERY = 'photogallery',

  LOGIN_FOR_ADMIN = 'admin-login',
  // пути для админки
  ADMIN = 'admin',
  ADMIN_MAIN = 'main',
  ADMIN_PROFILE = 'profile',
  ADMIN_USERS = 'users',
  ADMIN_HISTORY = 'history',
  ADMIN_SEO = 'seo',
  ADMIN_SUPER = 'super',
  ADMIN_BASE = 'base',

  ADMIN_PANEL_PRODUCTS = 'products',
  ADMIN_PANEL_CATEGORIES = 'categories',
  ADMIN_PANEL_GRIDS = 'grids',
  ADMIN_PANEL_NEWS = 'news',
  ADMIN_PANEL_MATERIALS = 'materials',
  ADMIN_PANEL_COLORS = 'colors',
  ADMIN_PANEL_COLORCATEGORIES = 'color_categories',
  ADMIN_PANEL_FURNITURES = 'furnitures',
  ADMIN_PANEL_ACTIONS = 'actions',
  ADMIN_PANEL_FASTENERS = 'fasteners',
  ADMIN_PANEL_SERIES = 'series',
  ADMIN_PANEL_TYPES = 'types',
  ADMIN_PANEL_SPECIFICATIONS = 'specifications',
  ADMIN_PANEL_MILLINGS = 'millings',
  ADMIN_PANEL_EDGES = 'edges',
  ADMIN_PANEL_COMBINE_MATERIALS = 'combine_materials',
  events = 'events',
}
